### ISSUE TITLE
afterFindでの取得処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/Tags#3]
現在、取得した$results毎に、Tagモデルのfindしてますが、$resultsの件数によっては重たくなる気がします。
IN句でまとめた方が、良いと思いますが、マージ処理が厄介な感じです。

キャッシュの利用とかですかね。。。
とりあえず、現状のまま、その他意見を待ちます。

**Comment by RyujiAMANO** [comment]
やるとしたら…
タグとコンテンツはn:nなので

1.リンクテーブルにタグをJOINしといてコンテンツIDをINまとめでFIND
2. コンテンツIDごとにリザルトに混ぜ込む

って感じですね。自動テストひととおり書けたらやってみるか…

**Comment by RyujiAMANO** [comment]
一旦保留とする
